### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by kezk** [huangyanbin/smartTable#10]
请问是否支持 ViewPager+Fragment

**Comment by huangyanbin** [comment]
没试过，你可以自己试试

**Comment by kezk** [comment]
试过了发现没有铺满屏幕

**Comment by huangyanbin** [comment]
截图来看看

**Comment by kezk** [comment]
![tim](https://user-images.githubusercontent.com/25544356/35368144-d488a99c-01bc-11e8-8b21-1d8c18c40990.png)

**Comment by huangyanbin** [comment]
那是因为你本身宽度就不够铺满屏幕哈

**Comment by kezk** [comment]
奥奥 谢了

**Comment by huangyanbin** [comment]
你觉得铺满屏幕需求大吗?大的话，我增加一个方法，可以设置显示最小宽度。这样你就可以把屏幕宽度设置进来。

**Comment by kezk** [comment]
如果列字段少的话一定会会有这样的需求的

**Comment by huangyanbin** [comment]
1.6.6版本已增加可设置表格最小宽度，会根据列比例铺满。
`table.getConfig().setMinTableWidth(screenWith);`

**Comment by kezk** [comment]
好的 非常感谢

**Comment by winston1991** [comment]
@kezk 会不会有滑动冲突啊

**Comment by winston1991** [comment]
@kezk @huangyanbin 我现在就是viewpager + fragment + smarttable 水平横向从右向左有冲突，smarttable滑动最右时 viewpager无法响应滑动事件

**Comment by kezk** [comment]
我当时用的没有使用滑动 




------------------ 原始邮件 ------------------
发件人: "wxishang"<notifications@github.com>; 
发送时间: 2019年7月31日(星期三) 下午2:00
收件人: "huangyanbin/smartTable"<smartTable@noreply.github.com>; 
抄送: "kenovice"<2244756710@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [huangyanbin/smartTable] 疑问 (#10)




@kezk 会不会有滑动冲突啊

**Comment by winston1991** [comment]
smarttable还没有填满屏幕吗还是刚刚填满屏幕？-------- 原始邮件 --------主题：Re: [huangyanbin/smartTable] 疑问 (#10)发件人：kezk 收件人：huangyanbin/smartTable 抄送：wxishang ,Comment 我当时用的没有使用滑动 



















------------------ 原始邮件 ------------------



发件人: "wxishang"<notifications@github.com>; 



发送时间: 2019年7月31日(星期三) 下午2:00



收件人: "huangyanbin/smartTable"<smartTable@noreply.github.com>; 



抄送: "kenovice"<2244756710@qq.com>; "Mention"<mention@noreply.github.com>; 



主题: Re: [huangyanbin/smartTable] 疑问 (#10)



















@kezk 会不会有滑动冲突啊



 



—



You are receiving this because you were mentioned.



Reply to this email directly, view it on GitHub, or mute the thread.



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/huangyanbin/smartTable/issues/10?email_source=notifications\u0026email_token=ABPNSPUPUUFNOHZDNBFJY7DQCET4DA5CNFSM4ENQ6SMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3GF7LQ#issuecomment-516710318",

"url": "https://github.com/huangyanbin/smartTable/issues/10?email_source=notifications\u0026email_token=ABPNSPUPUUFNOHZDNBFJY7DQCET4DA5CNFSM4ENQ6SMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3GF7LQ#issuecomment-516710318",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by kezk** [comment]
填满了 已经 具体的我记不清了 这个项目作者貌似已经放弃了 这个项目我已经舍弃它了






------------------ 原始邮件 ------------------
发件人: "wxishang"<notifications@github.com>; 
发送时间: 2019年7月31日(星期三) 下午2:16
收件人: "huangyanbin/smartTable"<smartTable@noreply.github.com>; 
抄送: "kenovice"<2244756710@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [huangyanbin/smartTable] 疑问 (#10)



smarttable还没有填满屏幕吗还是刚刚填满屏幕？-------- 原始邮件 --------主题：Re: [huangyanbin/smartTable] 疑问 (#10)发件人：kezk 收件人：huangyanbin/smartTable 抄送：wxishang ,Comment 我当时用的没有使用滑动  
 
 
 
 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 
 发件人: "wxishang"<notifications@github.com>;  
 
 发送时间: 2019年7月31日(星期三) 下午2:00 
 
 收件人: "huangyanbin/smartTable"<smartTable@noreply.github.com>;  
 
 抄送: "kenovice"<2244756710@qq.com>; "Mention"<mention@noreply.github.com>;  
 
 主题: Re: [huangyanbin/smartTable] 疑问 (#10) 
 
 
 
 
 
 
 
 
 
 @kezk 会不会有滑动冲突啊 
 
   
 
 — 
 
 You are receiving this because you were mentioned. 
 
 Reply to this email directly, view it on GitHub, or mute the thread. 
 
 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread. 
 [ 
 { 
 "@context": "http://schema.org", 
 "@type": "EmailMessage", 
 "potentialAction": { 
 "@type": "ViewAction", 
 "target": "https://github.com/huangyanbin/smartTable/issues/10?email_source=notifications\u0026email_token=ABPNSPUPUUFNOHZDNBFJY7DQCET4DA5CNFSM4ENQ6SMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3GF7LQ#issuecomment-516710318", 
 "url": "https://github.com/huangyanbin/smartTable/issues/10?email_source=notifications\u0026email_token=ABPNSPUPUUFNOHZDNBFJY7DQCET4DA5CNFSM4ENQ6SMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3GF7LQ#issuecomment-516710318", 
 "name": "View Issue" 
 }, 
 "description": "View this Issue on GitHub", 
 "publisher": { 
 "@type": "Organization", 
 "name": "GitHub", 
 "url": "https://github.com" 
 } 
 } 
 ]

**Comment by winston1991** [comment]
好的，谢谢啦-------- 原始邮件 --------主题：Re: [huangyanbin/smartTable] 疑问 (#10)发件人：kezk 收件人：huangyanbin/smartTable 抄送：wxishang ,Comment 填满了 已经 具体的我记不清了 这个项目作者貌似已经放弃了 这个项目我已经舍弃它了



























------------------ 原始邮件 ------------------



发件人: "wxishang"<notifications@github.com>; 



发送时间: 2019年7月31日(星期三) 下午2:16



收件人: "huangyanbin/smartTable"<smartTable@noreply.github.com>; 



抄送: "kenovice"<2244756710@qq.com>; "Mention"<mention@noreply.github.com>; 



主题: Re: [huangyanbin/smartTable] 疑问 (#10)















smarttable还没有填满屏幕吗还是刚刚填满屏幕？-------- 原始邮件 --------主题：Re: [huangyanbin/smartTable] 疑问 (#10)发件人：kezk 收件人：huangyanbin/smartTable 抄送：wxishang ,Comment 我当时用的没有使用滑动  



 



 



 



 



 



 



 



 



 



 ------------------ 原始邮件 ------------------ 



 



 发件人: "wxishang"<notifications@github.com>;  



 



 发送时间: 2019年7月31日(星期三) 下午2:00 



 



 收件人: "huangyanbin/smartTable"<smartTable@noreply.github.com>;  



 



 抄送: "kenovice"<2244756710@qq.com>; "Mention"<mention@noreply.github.com>;  



 



 主题: Re: [huangyanbin/smartTable] 疑问 (#10) 



 



 



 



 



 



 



 



 



 



 @kezk 会不会有滑动冲突啊 



 



   



 



 — 



 



 You are receiving this because you were mentioned. 



 



 Reply to this email directly, view it on GitHub, or mute the thread. 



 



 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread. 



 [ 



 { 



 "@context": "http://schema.org", 



 "@type": "EmailMessage", 



 "potentialAction": { 



 "@type": "ViewAction", 



 "target": "https://github.com/huangyanbin/smartTable/issues/10?email_source=notifications\u0026email_token=ABPNSPUPUUFNOHZDNBFJY7DQCET4DA5CNFSM4ENQ6SMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3GF7LQ#issuecomment-516710318", 



 "url": "https://github.com/huangyanbin/smartTable/issues/10?email_source=notifications\u0026email_token=ABPNSPUPUUFNOHZDNBFJY7DQCET4DA5CNFSM4ENQ6SMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3GF7LQ#issuecomment-516710318", 



 "name": "View Issue" 



 }, 



 "description": "View this Issue on GitHub", 



 "publisher": { 



 "@type": "Organization", 



 "name": "GitHub", 



 "url": "https://github.com" 



 } 



 } 



 ] 



—



You are receiving this because you were mentioned.



Reply to this email directly, view it on GitHub, or mute the thread.



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/huangyanbin/smartTable/issues/10?email_source=notifications\u0026email_token=ABPNSPR2XLPWEOC33DYTT33QCEVG3A5CNFSM4ENQ6SMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3GGX7I#issuecomment-516713469",

"url": "https://github.com/huangyanbin/smartTable/issues/10?email_source=notifications\u0026email_token=ABPNSPR2XLPWEOC33DYTT33QCEVG3A5CNFSM4ENQ6SMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3GGX7I#issuecomment-516713469",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
